### PR TITLE
[WALLPAPERS] Add data/ folder

### PR DESCRIPTION
**Pull request by katahiromz**
This PR will add `data/` folder with actual data files.
These data files will be stored into `%SystemRoot%\Web\Wallpaper`.

The Rapps data:
```ini
[Section]
Name = ReactOS Standard Wallpapers
Version = 2
License = CC BY
Description = The standard wallpaper collection for ReactOS
Category = 16
URLSite = https://github.com/reactos/wallpapers/
URLDownload = https://github.com/reactos/wallpapers/archive/refs/heads/main.zip
Installer = Generate
; SHA1 = ???
; SizeBytes = ???

[Generate]
Files = wallpapers-main\data\*
Dir = %SystemRoot%\Web\Wallpaper
Lnk = !
```

### CODE REVIEW

**Comment by katahiromz** [comment]
OK.

**Comment by katahiromz** [comment]
@learn-more Help me?

**Comment by learn-more** [comment]
> @learn-more Help me?

What is the question?

**Comment by katahiromz** [comment]
Can you merge this PR?

**Comment by learn-more** [comment]
> Can you merge this PR?

You should be able to do this yourself now.

**Comment by katahiromz** [comment]
Thank you.

**Pull request merged**
